### ISSUE TITLE
HLS based cache with Ariane

### ISSUE THREAD

**Issue by sanaallsanaall** [sld-columbia/esp#135]
I want to use the caches with single-core Ariane for the Xilinx VC707 board.
 
I aim at generating the caches with systemC.
Following the tutorial, I tried to issue the two commands "make llc-hls" and "make l2c-hls", but I got an error that seems to be a kind of bug.

In the GUI setting of the "esp-xconfig" command, I confirmed that I enabled the "use caches" and chose the "ESP HLS" as the implementation source.   

The below is the error log on the "make llc-hls" command.
make[1]: *** No rule to make target 'hls_all'.  Stop.
make[1]: *** No rule to make target 'hls_all', needed by 'install'.  Stop.

I really hope your help with this problem.
Thank you in advance.

This is the all message I got after performing the "make llc-hls" command. 
%make llc-hls && make l2c-hls
    MKDIR llc-wdir
    MAKE llc-hls
make[1]: Entering directory '/#home dir#/esp/rtl/caches/esp-caches/systemc/llc/hls-work-virtex7'
2021/12/13 13:20:40 WARNING This OS does not appear to be a Cadence supported Linux configuration.
2021/12/13 13:20:40 For more info, please run CheckSysConf in <cdsRoot/tools.lnx86/bin/checkSysConf <productId>
2021/12/13 13:20:40 WARNING This OS does not appear to be a Cadence supported Linux configuration.
2021/12/13 13:20:40 For more info, please run CheckSysConf in <cdsRoot/tools.lnx86/bin/checkSysConf <productId>
make[1]: 'memlib' is up to date.
make[1]: Leaving directory '/#home dir#/esp/rtl/caches/esp-caches/systemc/llc/hls-work-virtex7'
    INFO Running HLS for available implementations of llc
    MAKE llc-hls
make[1]: Entering directory '/#home dir#/esp/rtl/caches/esp-caches/systemc/llc/hls-work-virtex7'
2021/12/13 13:20:40 WARNING This OS does not appear to be a Cadence supported Linux configuration.
2021/12/13 13:20:40 For more info, please run CheckSysConf in <cdsRoot/tools.lnx86/bin/checkSysConf <productId>
2021/12/13 13:20:40 WARNING This OS does not appear to be a Cadence supported Linux configuration.
2021/12/13 13:20:40 For more info, please run CheckSysConf in <cdsRoot/tools.lnx86/bin/checkSysConf <productId>
make[1]: *** No rule to make target 'hls_all'.  Stop.
make[1]: Leaving directory '/#home dir#/esp/rtl/caches/esp-caches/systemc/llc/hls-work-virtex7'
    INFO Installing available implementations for llc to /#home dir#/esp/tech/virtex7/sccs/llc
    MAKE llc-hls
make[1]: Entering directory '/#home dir#/esp/rtl/caches/esp-caches/systemc/llc/hls-work-virtex7'
2021/12/13 13:20:40 WARNING This OS does not appear to be a Cadence supported Linux configuration.
2021/12/13 13:20:40 For more info, please run CheckSysConf in <cdsRoot/tools.lnx86/bin/checkSysConf <productId>
2021/12/13 13:20:40 WARNING This OS does not appear to be a Cadence supported Linux configuration.
2021/12/13 13:20:40 For more info, please run CheckSysConf in <cdsRoot/tools.lnx86/bin/checkSysConf <productId>
make[1]: *** No rule to make target 'hls_all', needed by 'install'.  Stop.
make[1]: Leaving directory '/#home dir#/esp/rtl/caches/esp-caches/systemc/llc/hls-work-virtex7'
/#home dir#/esp/utils/make/sc_caches.mk:36: recipe for target 'llc-hls' failed
make: *** [llc-hls] Error 2

**Comment by paulmnt** [comment]
The hls_all target not found is supposed to be part of the Stratus-generated Makefile.prj.

One possible issue is that the Makefile was not generated correctly, because you tried running the HLS targets without stratus in path. When that happens, some dependencies are created, but not completely, and following runs fail. If that were the case, the easy fix it to distclean (or remove) the HLS working folder, then try again with Stratus in path.

Other possible causes could be the version of Stratus, or the distro of Linux. Are you sure that  checkSysConf is not blocking the generation of the Makefile.prj?
If this is the issue, please make sure you run a version of Stratus/Linux that Cadence tools support. The versions for which ESP was tested are listed in the [setup guide](https://www.esp.cs.columbia.edu/docs/setup/setup-guide/).

hope this helps!
